config/routes.rb
Jba::Application.routes.draw do
  root :to => "welcome#home"
  resources :players

  get 'games' => "games#index"
  get 'teams' => "teams#index"
  get 'champions' => "champions#index"
  get 'login' => "sessions#new"
  get 'crossroad_games' => "games#crossroads"
  get 'wildcard_games' => "games#wildcard"
  get 'playoff_games' => "games#playoffs"
  get 'confirm_winner' => "games#confirm_winner"
  get 'show_team_record' => "teams#show_team_record"
  match 'assign_a_victor' => "games#assign_a_victor"

  match 'admin' => "admin#index"
  match 'confirm_admin' => "admin#confirm"
  match 'update_admin' => "admin#update"
  match "create_session" => "sessions#create"
  match "logout" => "sessions#destroy"
end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :position, :first_name, :last_name, :rating, :jersey_number, :free_agency, :team_id
end

app/models/players.rb
class Players < ActiveRecord::Base
  attr_accessible :first_name, :free_agency, :jersey_number, :last_name, :position, :team_id
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :check_if_logged_in
  def index
    @players = Player.order('rating DESC')

    respond_to do |format|
      format.html
      format.json { render json => @players }
    end
  end

  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json => @player }
    end
  end

  def new
    @player = Player.new

    respond_to do |format|
      format.html
      format.json { render json => @player }
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice => 'Player was successfully created.' }
        format.json { render json => @player, status => :created, location => @player }
      else
        format.html { render action => "new" }
        format.json { render json => @player.errors, status => :unprocessable_entity }
      end
    end
  end

  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice => 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action => "edit" }
        format.json { render json => @player.errors, status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/players_helper.rb
module PlayersHelper
  def teams
    teams = []
    Team.all.each do |team|
      teams << (full_name_of team)
    end
    return teams
  end

  def current_year
    User.first.current_year
  end

  def positions
    ['PG','SG','SF','PF','C']
  end

  def rating_range
    70..99
  end

  def jersey_number_range
    00..99
  end

  def free_agency_year
    current_year..(current_year+6)
  end

  def teams_used_for_select
    Team.all.collect {|t| [(full_name_of t), t.id]}
  end
end

app/views/players/_form.html.haml
= form_for @player do |f|
  - if @player.errors.any?
    #error_explanation
      %h2= "#{pluralize(@player.errors.count, "error")} prohibited this player from being saved:"
      %ul
        - @player.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :team
    = select :player,:team_id, teams_used_for_select
  .field
    = f.label :free_agency
    = select :player, :free_agency, free_agency_year
  .field
    = f.label :jersey_number
    = select :player, :jersey_number, jersey_number_range
  .field
    = f.label :rating
    = select :player, :rating, rating_range
  .field
    = f.label :position
    = select :player, :position, positions
  .actions
    = f.submit 'Save'

app/views/players/_show_players.html.haml
%table.table.table-bordered.table-striped
  %tr
    %th Position
    %th First name
    %th Last name
    %th Rating
    %th Jersey Number
    %th Free Agency
    %th Team
    %th
    %th

  - @players.each do |player|
    %tr
      %td= player.position
      %td= player.first_name
      %td= player.last_name
      %td= player.rating
      %td= player.jersey_number
      %td= player.free_agency
      %td= full_name_of Team.find(player.team_id)
      %td= link_to 'Show', player
      %td= link_to 'Edit', edit_player_path(player)

app/views/players/edit.html.haml
%h1 Editing player

= render 'form'

= link_to 'Show', @player
\|
= link_to 'Back', players_path

app/views/players/index.html.haml
%h1 Listing players

= render 'show_players'

%br

= link_to 'New Player', new_player_path

app/views/players/new.html.haml
%h1 New player

= render 'form'

= link_to 'Back', players_path

app/views/players/show.html.haml
%p#notice= notice

%p
  %b Position:
  = @player.position
%p
  %b First name:
  = @player.first_name
%p
  %b Last name:
  = @player.last_name
%p
  %b Rating
  = @player.rating
%p
  %b Jersey number:
  = @player.jersey_number
%p
  %b Free agency:
  = @player.free_agency
%p
  %b Team:
  = full_name_of Team.find @player.team_id

= link_to 'Edit', edit_player_path(@player)
\|
= link_to 'Back', players_path